image: alpine

stages:
  - build

build jpegoptim:
  image: docker:dind
  stage: build
  script:
    # install composer and get dependencies
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
    - docker build -t turion/jpegoptim -f Dockerfile .
    - docker push turion/jpegoptim
  only:
    - master